# Site settings
title: Yann Herklotz
description: >-
  Game engine C++ developer, with a passion for functional programming
url: https://ymherklotz.github.io/
baseurl:
# url: "localhost:3000"

# User settings
username: Yann Herklotz
user_title: Software Developer
email: yann@ymhg.org
twitter_username: ymherklotz
github_username: ymherklotz
linkedin_username: yannherklotz

markdown: kramdown

collections:
  portfolio:
    output: true

# Google-analytics
google-analytics:
  id: "UA-120899424-1"

exclude:
  - package.json
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
