# Site settings
title: Yann Herklotz
description: Personal website for blogs and projects.
baseurl: "/"
url: "www.yannherklotz.com"

# User settings
username: Yann Herklotz
user_description: >
  Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a
  bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters
  pour-over snackwave you probably haven't heard of them small batch. Cornhole
  mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: ymherklotz@gmail.com
twitter_username: ymherklotz
github_username: ymherklotz
linkedin_username: yannherklotz

# Google-analytics
google-analytics:
  id: "UA-120899424-1"

exclude:
  - package.json
  - src
  - node_modules
